tab_spaces = 4
max_width = 80
brace_style = "Always"
hard_tabs = false
format_strings = true
format_macro_matchers = true
format_code_in_doc_comments = true
remove_blank_lines_at_start_or_end_of_block = true